# Auto-generated by /home/osboxes/fix_rttee_text/RT-TEE/build/../edk2/BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/home/osboxes/fix_rttee_text/RT-TEE/build/../edk2
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/home/osboxes/rttee_qemu/build/../edk2/BaseTools
fi
if [ -e /home/osboxes/rttee_qemu/build/../edk2/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//home/osboxes/rttee_qemu/build/../edk2/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/home/osboxes/rttee_qemu/build/../edk2/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
